name = "cfcap"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "R2_CHALLENGES"
bucket_name = "cap-challenges"

[[r2_buckets]]
binding = "R2_TOKENS"
bucket_name = "cap-tokens"

[vars]
ALLOWED = "*.secops.workers.dev,fast.secw.net,speed.secw.net,*.kalman.co.il"
CHALLENGE_TTL = 300
TOKEN_TTL = 330
