name = "cfcap"
main = "src/index.js"
compatibility_date = "2024-12-05"

[observability]
enabled = true

[assets]
directory = "dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "R2_CHALLENGES"
bucket_name = "cap-challenges"

[[r2_buckets]]
binding = "R2_TOKENS"
bucket_name = "cap-tokens"
